version: "3.8"

services:
  reading-api:
    container_name: reading-api-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - .:/src
    platform: linux/amd64
    env_file: .env
    command: >
      sh -c "uvicorn app.main:fastapi_app --host 0.0.0.0 --port 7000 --reload"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: "db"
    image: postgres:16
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - dev-db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    platform: linux/amd64

volumes:
  dev-db:
